name: Despliegue de Backend en prd

on:
  push:
    branches:
      - master  # Ajusta esto a la rama donde quieres realizar el despliegue

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configura Node.js  # Asumiendo que tu backend es Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.18'  # Ajusta esto a tu versión de Node.js

    - name: Instala dependencias
      run: npm install

    - name: Ejecuta master
      run: npm run test  # Ajusta esto según tu comando para pruebas


